default_install_hook_types:
  - pre-commit
  - commit-msg

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-json
      - id: check-added-large-files
  - repo: https://github.com/compilerla/conventional-pre-commit
    rev: v4.4.0
    hooks:
      - id: conventional-pre-commit
        stages: [commit-msg]
        args: []
  - repo: https://github.com/tekwizely/pre-commit-golang
    rev: v1.0.0-rc.4
    hooks:
      # Formatting
      - id: go-fmt-repo
        name: go fmt (repo root)

      # Dependency management
      - id: go-mod-tidy-repo
        name: go mod tidy (all modules)

      # Static analysis
      - id: go-vet-repo-mod
        name: go vet (all modules)

      # Compilation check
      - id: go-build-repo-mod
        name: go build (all modules)

      # Testing
      - id: go-test-mod
        name: go test (each staged .go file)
